# Generated by Django 5.2.3 on 2025-07-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Internship', 'Internship'), ('Part-time', 'Part-time'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_date',
            field=models.DateField(),
        ),
    ]
