# Generated by Django 5.2.3 on 2025-08-05 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_savedjob_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='start_date',
        ),
    ]
