# Generated by Django 5.2.3 on 2025-07-31 13:32

import accounts.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_profile_pic_alter_profile_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, null=True, storage=accounts.storages.RawMediaCloudinaryStorage(), upload_to='resumes/'),
        ),
    ]
