# Generated by Django 5.2.3 on 2025-09-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_pendinguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='last_otp_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
