# Generated by Django 5.2.3 on 2026-02-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_pendinguser_last_otp_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
